[theme]
base="dark"
primaryColor="#90d5ff"
primaryColor="90D5FF"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[server]
enableCORS=false
enableXsrfProtection=false
maxUploadSize = 1500