# Theme config
[theme]
base = "dark"
primaryColor = "#90D5FF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 1500