# Theme config
[theme]
base = "dark"
primaryColor = "#0096FF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"

[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 1500