AVIATIONSTACK_API_KEY = '04360d2c8eff0da265c69169b6e68b87'
NEWS_API_KEY = 'ca573d9ef5824ade877db187b4fe3b77'

[connections.mysql]
dialect="mysql"
host="localhost"
port=3306
database="KAGGLE"
username="root"
password="CombatArms12"