AVIATIONSTACK_API_KEY = '04360d2c8eff0da265c69169b6e68b87'
NEWS_API_KEY = 'ca573d9ef5824ade877db187b4fe3b77'
CAT_API_KEY = 'live_SNJzIG3FX4dUQKIzOy9Fc0KMAl6pdtJvbn59ygPHZTjtmy1UsGMtoLACZ2mEuSAe'
TASTY_DIVE_KEY = '1065226-Streamli-8E54CAE7'
ADMIN_PASSWORD = 'CombatArms12'

[connections.mysql]
dialect="mysql"
host="localhost"
port=3306
database="KAGGLE"
username="root"
password="CombatArms12"